
// For LOGIN API
export const SET_ADMIN_DATA = 'SET_ADMIN_DATA';


// For LOGIN API
export const UPDATE_USER_REQUEST = 'UPDATE_COMPANIES_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_COMPANIES_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_COMPANIES_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_COMPANIES_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_COMPANIES_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_COMPANIES_FAILURE';

// For COMPANIES API
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_FAILURE = 'FETCH_CLIENTS_FAILURE';
export const CLIENT_DETAILS_UPDATE = 'CLIENT_DETAILS_UPDATE';

export const ADD_COMPANIES_REQUEST = 'ADD_COMPANIES_REQUEST';
export const ADD_COMPANIES_SUCCESS = 'ADD_COMPANIES_SUCCESS';
export const ADD_COMPANIES_FAILURE = 'ADD_COMPANIES_FAILURE';

export const UPDATE_COMPANIES_REQUEST = 'UPDATE_COMPANIES_REQUEST';
export const UPDATE_COMPANIES_SUCCESS = 'UPDATE_COMPANIES_SUCCESS';
export const UPDATE_COMPANIES_FAILURE = 'UPDATE_COMPANIES_FAILURE';

export const DELETE_COMPANIES_REQUEST = 'DELETE_COMPANIES_REQUEST';
export const DELETE_COMPANIES_SUCCESS = 'DELETE_COMPANIES_SUCCESS';
export const DELETE_COMPANIES_FAILURE = 'DELETE_COMPANIES_FAILURE';


