
import { AiOutlineMessage, AiOutlineSetting, AiOutlineTeam, AiOutlineCalendar, AiOutlineFolderOpen, AiOutlineWhatsApp, AiOutlineMore, AiOutlineCloudServer, AiOutlineAccountBook  } from "react-icons/ai";
import { BsChatText, BsPeople, BsGearWideConnected, BsBoxArrowInUpRight } from "react-icons/bs";
import { FaPlusCircle, FaRegEdit, FaTrash, FaRegUser, FaSort, FaSortDown, FaSortUp } from "react-icons/fa";
import { MoreOutlined, InfoCircleOutlined, CloudSyncOutlined, CloudDownloadOutlined, DownOutlined } from '@ant-design/icons';
import { FiEdit2 } from "react-icons/fi";
import { IoDuplicateSharp, IoBusinessOutline } from "react-icons/io5";
import { HiOutlineCurrencyRupee } from "react-icons/hi2";
import {  FiEye } from "react-icons/fi";

export const ICAiOutlineSetting = () => { return <AiOutlineSetting color="#673275" /> };
export const ICAiOutlineCalendar = () => { return <AiOutlineCalendar color="#673275" /> };
export const ICAiOutlineMessage = () => { return <AiOutlineMessage color="#673275" /> };
export const ICAiOutlineTeam = () => { return <AiOutlineTeam color="#673275" /> };
export const ICFaRegUser = () => { return <FaRegUser color="#673275" /> };
export const ICFaTrash = () => { return <FaTrash color="#673275" /> };
export const ICFiEye = () => { return <FiEye color="#673275" /> };
export const ICFiEdit2 = () => { return <FiEdit2 color="#673275" /> };
export const ICFaRegEdit = () => { return <FaRegEdit color="#673275" /> };
export const ICFaPlusCircle = () => { return <FaPlusCircle color="#673275" /> };
export const ICBsPeople = () => { return <BsPeople color="#673275" /> };
export const ICBsChatText = () => { return <BsChatText color="#673275" /> };
export const ICMoreOutlined = () => { return <MoreOutlined rev="" color="#673275" /> };
export const ICInfoCircleOutlined = () => { return <InfoCircleOutlined rev="" color="#673275" /> };
export const ICIoDuplicateSharp = () => { return <IoDuplicateSharp color="#673275" /> };
export const ICCloudSyncOutlined = () => { return <CloudSyncOutlined rev="" color="#673275" /> };
export const ICDownOutlined = () => { return <DownOutlined rev="" color="#673275" /> };
export const ICCloudDownloasOutlined = () => { return <CloudDownloadOutlined rev="" color="#673275" /> };
export const ICAiOutlineWhatsappWeb = () => { return <AiOutlineWhatsApp color="#673275" /> };
export const ICAiOutlineMore = () => { return <AiOutlineMore color="#673275" /> };
export const ICBsGearWideConnected = () => { return <BsGearWideConnected color="#673275" /> };
export const ICFaSort = () => { return <FaSort color="#673275" /> };
export const ICFaSortDown = () => { return <FaSortDown color="#673275" /> };
export const ICFaSortUp = () => { return <FaSortUp color="#673275" /> };
export const ICFBsBoxArrowInUpRight = () => { return <BsBoxArrowInUpRight color="#673275" /> };
export const ICAiOutlineCloudServer = () => { return <AiOutlineCloudServer color="#673275" /> };
export const ICIoBusinessOutline = () => { return <IoBusinessOutline color="#673275" /> };
export const ICAiOutlineAccountBook = () => { return <AiOutlineAccountBook color="#673275" /> };
export const ICAiOutlineFolderOpen = () => { return <AiOutlineFolderOpen color="#673275" /> };
export const ICHiOutlineCurrencyRupee = () => { return <HiOutlineCurrencyRupee color="#673275" /> };
